id: P87DE2185
initial_creation_type: ocr
source_metadata:
  volumes:
    38db015206fe4d1eb08fd4c2c097fddb:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཇིག་རྟེན་དབང་ཕྱུག་གི་སྒྲུབ་ཐབས།
      total_pages: 1379
      volume_number: 37
