id: P87DE2185
initial_creation_type: ocr
source_metadata:
  volumes:
    4b279e049ffc4774a8a7687cf5b2dee7:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: འཇིག་རྟེན་དབང་ཕྱུག་གི་སྒྲུབ་ཐབས།
      total_pages: 1648
      volume_number: 40
