id: D1837CCF0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-06T09:37:38+00:00'
last_modified: '2022-05-26T12:12:57.014314+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    85fd:
      image_group_id: I1PD95882
      title: འཇིག་རྟེན་དབང་ཕྱུག་གི་སྒྲུབ་ཐབས།
      total_pages: 1379
      order: 37
      base_file: 85fd.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
